In [2]:
import storytime as s

In [3]:
s.world.World

storytime.world._world.World

In [2]:
import networkx as nx
import matplotlib.pyplot as plt
import matplotlib

import numpy as np

from scipy.spatial import Voronoi, voronoi_plot_2d
# import shapely.geometry
# import shapely.ops


In [28]:
x_size = 200
y_size = 100
tile_area  = 1
total_area = x_size * y_size
num_tiles  = total_area / tile_area


points = np.random.random( (total_area, 2) )

p2     = np.array([(x * x_size, y * y_size) for (x,y) in points])
vor    = Voronoi(p2)

display(vor.points)
len(points)

array([[  6.37497196,  87.20550193],
       [129.65232673,  45.36324604],
       [ 28.34772469,  66.34766616],
       ...,
       [ 30.31330511,  47.22057445],
       [155.17102185,  54.8891322 ],
       [186.6259103 ,  34.28653803]])

20000

In [20]:
vor.vertices

array([[200.12534286,  99.40515844],
       [199.92000168,   1.28841577],
       [199.59160925,   0.49214842],
       ...,
       [ 66.58676146,  96.04189177],
       [ 65.73788603,  95.93603568],
       [ 65.74369146,  96.06183365]])

In [21]:
fig = voronoi_plot_2d( vor )
fig.set_size_inches(200, 100)
#matplotlib.pyplot.show()
fig.savefig('test.png', dpi=100)

In [22]:
fig = vor.regions

In [23]:
vor.point_region

array([17425, 14133,   949, ..., 19589, 10859, 14511], dtype=int64)

In [24]:
vor.ridge_dict

{(11069, 9938): [2, 4],
 (11069, 578): [2, 3],
 (11069, 13750): [3, 5],
 (11069, 17137): [4, 5],
 (9938, 578): [-1, 2],
 (9938, 5663): [-1, 1],
 (9938, 17137): [1, 4],
 (3728, 5835): [70, 71],
 (3728, 1706): [70, 72],
 (3728, 4275): [71, 74],
 (3728, 9840): [72, 73],
 (3728, 17931): [73, 74],
 (5835, 8761): [26, 27],
 (5835, 9170): [26, 28],
 (5835, 4275): [27, 71],
 (5835, 1706): [28, 70],
 (4275, 17931): [14, 74],
 (4275, 8761): [14, 27],
 (9840, 17043): [29, 30],
 (9840, 17931): [29, 73],
 (9840, 1706): [30, 72],
 (17931, 8761): [14, 66],
 (17931, 17043): [29, 78],
 (17931, 11749): [66, 79],
 (17931, 11217): [78, 79],
 (11522, 17043): [80, 84],
 (11522, 18658): [80, 82],
 (11522, 5701): [81, 82],
 (11522, 2396): [81, 83],
 (11522, 1706): [83, 84],
 (17043, 1706): [30, 84],
 (17043, 11217): [77, 78],
 (17043, 18658): [77, 80],
 (18658, 5701): [75, 82],
 (18658, 4176): [75, 76],
 (18658, 11217): [76, 77],
 (8081, 13242): [92, 94],
 (8081, 7467): [92, 93],
 (8081, 5527): [93, 94],
 (17

In [25]:
vor.ridge_points

array([[11069,  9938],
       [11069,   578],
       [11069, 13750],
       ...,
       [ 4778,  6005],
       [ 6005,  5492],
       [ 5492, 10319]], dtype=int32)

In [26]:
vor.ridge_vertices

[[2, 4],
 [2, 3],
 [3, 5],
 [4, 5],
 [-1, 2],
 [-1, 1],
 [1, 4],
 [70, 71],
 [70, 72],
 [71, 74],
 [72, 73],
 [73, 74],
 [26, 27],
 [26, 28],
 [27, 71],
 [28, 70],
 [14, 74],
 [14, 27],
 [29, 30],
 [29, 73],
 [30, 72],
 [14, 66],
 [29, 78],
 [66, 79],
 [78, 79],
 [80, 84],
 [80, 82],
 [81, 82],
 [81, 83],
 [83, 84],
 [30, 84],
 [77, 78],
 [77, 80],
 [75, 82],
 [75, 76],
 [76, 77],
 [92, 94],
 [92, 93],
 [93, 94],
 [1, 99],
 [5, 100],
 [99, 100],
 [95, 96],
 [95, 121],
 [96, 122],
 [121, 122],
 [42, 143],
 [42, 43],
 [43, 144],
 [143, 144],
 [142, 148],
 [142, 146],
 [146, 148],
 [149, 150],
 [149, 153],
 [150, 151],
 [151, 152],
 [152, 153],
 [44, 145],
 [44, 49],
 [49, 155],
 [145, 156],
 [155, 156],
 [198, 201],
 [198, 199],
 [199, 202],
 [200, 201],
 [200, 203],
 [202, 203],
 [195, 197],
 [195, 203],
 [197, 200],
 [-1, 13],
 [-1, 55],
 [13, 56],
 [55, 205],
 [56, 206],
 [205, 206],
 [10, 275],
 [10, 258],
 [258, 259],
 [259, 261],
 [260, 261],
 [260, 277],
 [275, 277],
 [279, 280],
